apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-pull-integration-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-pull-integration
subjects:
- kind: ServiceAccount
  name: argocd-pull-integration
  namespace: argocd
