//go:build !ignore_autogenerated

/*
Copyright 2025 Open Cluster Management.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDAgentAddonSpec) DeepCopyInto(out *ArgoCDAgentAddonSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDAgentAddonSpec.
func (in *ArgoCDAgentAddonSpec) DeepCopy() *ArgoCDAgentAddonSpec {
	if in == nil {
		return nil
	}
	out := new(ArgoCDAgentAddonSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsCluster) DeepCopyInto(out *GitOpsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsCluster.
func (in *GitOpsCluster) DeepCopy() *GitOpsCluster {
	if in == nil {
		return nil
	}
	out := new(GitOpsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsClusterList) DeepCopyInto(out *GitOpsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitOpsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsClusterList.
func (in *GitOpsClusterList) DeepCopy() *GitOpsClusterList {
	if in == nil {
		return nil
	}
	out := new(GitOpsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitOpsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsClusterSpec) DeepCopyInto(out *GitOpsClusterSpec) {
	*out = *in
	out.PlacementRef = in.PlacementRef
	out.ArgoCDAgentAddon = in.ArgoCDAgentAddon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsClusterSpec.
func (in *GitOpsClusterSpec) DeepCopy() *GitOpsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GitOpsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsClusterStatus) DeepCopyInto(out *GitOpsClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsClusterStatus.
func (in *GitOpsClusterStatus) DeepCopy() *GitOpsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GitOpsClusterStatus)
	in.DeepCopyInto(out)
	return out
}
