apiVersion: apps.open-cluster-management.io/v1alpha1
kind: GitOpsCluster
metadata:
  name: {{ .Values.gitOpsCluster.name }}
  namespace: {{ .Values.gitOpsCluster.namespace }}
spec:
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: placement
  argoCDAgentAddon:
    {{- if .Values.gitOpsCluster.principalServerAddress }}
    principalServerAddress: {{ .Values.gitOpsCluster.principalServerAddress }}
    {{- end }}
    {{- if .Values.gitOpsCluster.principalServerPort }}
    principalServerPort: {{ .Values.gitOpsCluster.principalServerPort | quote }}
    {{- end }}
    mode: {{ .Values.gitOpsCluster.mode }}
    {{- if .Values.gitOpsCluster.argoCDAgentAddon.agentNamespace }}
    agentNamespace: {{ .Values.gitOpsCluster.argoCDAgentAddon.agentNamespace }}
    {{- end }}
    {{- if .Values.gitOpsCluster.argoCDAgentAddon.operatorNamespace }}
    operatorNamespace: {{ .Values.gitOpsCluster.argoCDAgentAddon.operatorNamespace }}
    {{- end }}
    {{- if .Values.gitOpsCluster.customArgoCDCR.enabled }}
    argoCDCRManifestWork:
      manifests:
      - apiVersion: argoproj.io/v1beta1
        kind: ArgoCD
        metadata:
          name: argocd
          namespace: {{ .Values.gitOpsCluster.argoCDAgentAddon.agentNamespace | default "argocd" }}
        spec:
          server:
            enabled: false
          sourceNamespaces:
          - "*"
          argoCDAgent:
            agent:
              enabled: true
              allowedNamespaces:
              - "*"
              destinationBasedMapping:
                enabled: true
                createNamespace: true
              creds: "mtls:open-cluster-management:cluster:([^:]+):addon:argocd-agent"
              logLevel: "info"
              logFormat: "text"
              client:
                mode: {{ .Values.gitOpsCluster.mode }}
                enableWebSocket: false
                enableCompression: false
                keepAliveInterval: "50s"
              tls:
                secretName: "argocd-agent-open-cluster-management.io-argocd-agent-addon-client-cert"
                rootCASecretName: "argocd-agent-ca"
                insecure: false
              redis:
                serverAddress: "argocd-redis:6379"
    {{- end }}
