name: FOSSA License Scan

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Run FOSSA Scan
        uses: fossas/fossa-action@ff70fe9fe17cbd2040648f1c45e8ec4e4884dcf3 # v1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
